### ISSUE TITLE
React Router Links Broken

### ISSUE THREAD

**Issue by HarshKhandeparkar** [gpujs/gpu.rocks#16]
> When on https://gpu.rocks/ the top navigation links work as expected. If i am on any of those pages and hit F5 or move fwd/back with browser controls the links all go to a 404 error page. Only way to get to various pages it to get back to https://gpu.rocks/ and use the top navigation links. Frustrating...

Pointed out by @chachew

**Comment by Mluckydwyer** [comment]
### **Problem**
I have had similar issues on a previous project based in React. As I am sure you are aware, in react when a user clicks on a link to navigate to a new page, no actual page redirection occurs in the sense that we are normally used to. You remain on the same HTML page, but the underlying JAvascript that is generated when you build your site changes the elements displayed and the URL shown as if a redirection has occurred. All links work when a visitor's navigation begins on the home page. This is because on this page, the base index.html file is located by the browser and loaded, and that intern loads the underlying javascript to handle all of the React components and page redirection. Since in theory you never leave the initial page, the javascript stays loaded and in control and all works as expected. As you stated, when trying to navigate to a page directly through a URL or navigating backwards or forwards, the browser attempts to find an HTML file and page that does not exist since the JS of React has been doing the heavy-lifting in the background unannounced to the browser.

### **Possible Solutions:**
With my understanding (albeit limited) of React, you have 3 solutions to your issue.

1. Host your server on Node.js with React running on the server-side. This would mean you have the same React framework running in both the browser and server, thus the react-router on the backend would handle the scenarios where the browser fails and load content accordingly.

2. Adjust your webserver settings to redirect all requests for pages to the root directly/homepage where you have your HTML file sitting. This would reload the HTML and React JS and react would interpret the URL and render the page accordingly.

3. Place a base index.html file in each directory where there is a page a user could visit. This is the messiest solution, but it would solve your problem and still allow you to use React on Github Pages. Anytime a user visits any page, they would load the respective index.html file in that directory. These can all be the same as the root/homepage index.html, as their only purpose is to load the React Javascript. This intern will then work the same as the previous solution, as React would then take the URL and interpret it as expected.

### **Resources**
Here are a few resources that explain this better than I can and helped me to ultimately solve this problem in the past:
[Stack Overflow Answer](https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually?page=1&tab=votes#tab-top)

**Comment by Mluckydwyer** [comment]
I would be happy to try and help you with this issue. I can try and put up a pull request once I can get the node modules to properly install on my local machine.

**Comment by HarshKhandeparkar** [comment]
@Mluckydwyer Thanks a lot for your help. I read through all the solutions and I don't think the first two are viable as we don't use our own servers but use github pages.

I don't know whether the third solution will work but I'll try it out.

My idea was to use a service worker to load the JS before the browser tries to load any HTML. Do you think we could pull this off?

**Comment by Mluckydwyer** [comment]
That might also work as a possible solution. I tried again recently and I still have yet to get the "gl" package to build and install properly on either Windows or Linux, otherwise I would have submitted a PR by now.

**Comment by HarshKhandeparkar** [comment]
Did you follow the instructions present on the gpu.js README? If not,
please do so. It has some system dependency installation steps. Sorry for
the inconvenience.

**Comment by robertleeplummerjr** [comment]
I always take a gander at https://github.com/stackgl/headless-gl, and it helps me if I'm stuck installing GPU.js.

**Comment by HarshKhandeparkar** [comment]
Fixed in https://github.com/gpujs/gpu.rocks/commit/1167140cefc00a33d33200391b8f2cf62abd9700. Ty all!
