### ISSUE TITLE
Benchmark not working

### ISSUE THREAD

**Issue by Benoit9** [gpujs/gpu.rocks#20]
I tried http://gpu.rocks/#/benchmark on several browsers and different machines: I don't see any result. The buttons animates, then nothing.

**Comment by HarshKhandeparkar** [comment]
This is happening because it is using an incompatible version of gpu.js for whatever reason.

My plan is: 
1. Release gpujs/benchmark v3.0.1 which doesn't ship with a version of gpu.js
2. Use this new version
3. Switch to react instead of DOM manipulation like it does now. I had to do it because there wasn't a good way to get form inputs in react back then.

**Comment by HarshKhandeparkar** [comment]
Fixed just now. Ty @Benoit9
